version: '3'

services:
  mongodb:
    container_name: mongodb-server
    image: mongo
    restart: always
    ports:
      - '27017:27017'
  volumes:
    - myapp:/data/db
  networks:
    - backend-net

networks:
  backend-net:

volumes:
  myapp:
    external: true
